-- 004_seed_source_configs.sql

insert into public.qlik_source_configs (
  sync_key,
  hub_page,
  hub_visualization,
  hub_visualization_description,
  qlik_app_id,
  qlik_sheet_id,
  qlik_object_id,
  qlik_object_description,
  domain_name,
  target_table_name,
  primary_key_strategy
)
values
  (
    'home_canopy_production_last_12_months',
    'Home',
    'Canopy Production Last 12 Months',
    'The bars are funded loan counts and the line shows the funded loan volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_division_leaderboard_production_data',
    'Home',
    'Division Leaderboard',
    'A monthly ranking of all of our divisions by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_division_leaderboard_divisions',
    'Home',
    'Division Leaderboard',
    'A monthly ranking of all of our divisions by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '657aeffc-04db-49f6-b53f-5df33e256df4',
    'Divisions',
    'divisions',
    'divisions',
    'natural_key'
  ),
  (
    'home_branch_leaderboard_production_data',
    'Home',
    'Branch Leaderboard',
    'A monthly ranking of all of our branches by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_branch_leaderboard_branches',
    'Home',
    'Branch Leaderboard',
    'A monthly ranking of all of our branches by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '52e19a8d-27b8-485a-b3fd-754625dfc11f',
    'Branches',
    'branches',
    'branches',
    'natural_key'
  ),
  (
    'home_loan_officer_leaderboard_production_data',
    'Home',
    'Loan Officer Leaderboard',
    'A monthly ranking of all of our loan officers by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_loan_officer_leaderboard_employee_data',
    'Home',
    'Loan Officer Leaderboard',
    'A monthly ranking of all of our loan officers by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '99cffdd8-c4c2-44d6-adf3-a39bc721903f',
    'Employee Data',
    'employees',
    'employees',
    'natural_key'
  ),
  (
    'home_processor_leaderboard_production_data',
    'Home',
    'Processor Leaderboard',
    'A monthly ranking of all of our processors by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_processor_leaderboard_employee_data',
    'Home',
    'Processor Leaderboard',
    'A monthly ranking of all of our processors by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '99cffdd8-c4c2-44d6-adf3-a39bc721903f',
    'Employee Data',
    'employees',
    'employees',
    'natural_key'
  ),
  (
    'home_underwriter_leaderboard_production_data',
    'Home',
    'Underwriter Leaderboard',
    'A monthly ranking of all of our underwriters by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_underwriter_leaderboard_employee_data',
    'Home',
    'Underwriter Leaderboard',
    'A monthly ranking of all of our underwriters by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '99cffdd8-c4c2-44d6-adf3-a39bc721903f',
    'Employee Data',
    'employees',
    'employees',
    'natural_key'
  ),
  (
    'home_underwriting_org_leaderboard_production_data',
    'Home',
    'Underwriting Org Leaderboard',
    'A monthly ranking of all of our underwriting orgs by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'home_underwriting_org_leaderboard_underwriting_orgs',
    'Home',
    'Underwriting Org Leaderboard',
    'A monthly ranking of all of our underwriting orgs by funded loan count (new monthly ranking starts on the 5th). Also shows volume.',
    '49464eb8-41f0-499e-87dd-4a95f9341785',
    'dTpmk',
    'c0745582-e2c1-41e4-ab29-4381213f8938',
    'Underwriting Orgs',
    'raw_only',
    null,
    'hash'
  ),
  (
    'home_corporate_turn_times',
    'Home',
    'Corporate Turn Times',
    'A panel that contains a table and some KPI''s. Let me know if you have questions.',
    'e994317a-0430-42f9-8561-04c6bd6c684d',
    'jyXd',
    'yyvaTp',
    'Corporate Turn Times',
    'corporate_turn_times',
    'corporate_turn_times',
    'hash'
  ),
  (
    'home_funded_loans_by_loan_program',
    'Home',
    'Funded Loans by Loan Program',
    'A pie chart tracking file counts of funded loans for each loan program.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'file_quality_by_division_file_quality_data',
    'File Quality',
    'By Division',
    'A monthly ranking of file quality metrics by funded date. Lowest number of average net touches are at the top. Users can select other months to view, but the sheet defaults to last month.',
    'c606ead6-932c-4cad-8466-5e2721114999',
    'jwabcU',
    'jdnBbh',
    'File Quality Data',
    'file_quality_data',
    'file_quality_data',
    'natural_key'
  ),
  (
    'file_quality_by_division_divisions',
    'File Quality',
    'By Division',
    'A monthly ranking of file quality metrics by funded date. Lowest number of average net touches are at the top. Users can select other months to view, but the sheet defaults to last month.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '657aeffc-04db-49f6-b53f-5df33e256df4',
    'Divisions',
    'divisions',
    'divisions',
    'natural_key'
  ),
  (
    'file_quality_by_branch_file_quality_data',
    'File Quality',
    'By Branch',
    'A monthly ranking of file quality metrics by funded date. Lowest number of average net touches are at the top. Users can select other months to view, but the sheet defaults to last month.',
    'c606ead6-932c-4cad-8466-5e2721114999',
    'jwabcU',
    'jdnBbh',
    'File Quality Data',
    'file_quality_data',
    'file_quality_data',
    'natural_key'
  ),
  (
    'file_quality_by_branch_branches',
    'File Quality',
    'By Branch',
    'A monthly ranking of file quality metrics by funded date. Lowest number of average net touches are at the top. Users can select other months to view, but the sheet defaults to last month.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '52e19a8d-27b8-485a-b3fd-754625dfc11f',
    'Branches',
    'branches',
    'branches',
    'natural_key'
  ),
  (
    'pipeline_active_files',
    'Pipeline',
    'Active Files',
    'Users'' active pipelines with row-level security to display unique pipelines for each user.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'KmWTRR',
    'mjKyjmn',
    'Production Data',
    'production_data',
    'production_data',
    'natural_key'
  ),
  (
    'points_specialists_point_summary_old',
    'Points - Specialists',
    'Point Summary',
    'A bar chart showing monthly totals of points going back 12 months. Filterable by PA org.',
    'c499088a-8488-4839-b730-df1231e0f41b',
    'GrjAkg',
    'dZfMkdf',
    'Specialist Points Data (old)',
    'specialist_points_old',
    'specialist_points_old',
    'natural_key'
  ),
  (
    'points_specialists_point_summary_new',
    'Points - Specialists',
    'Point Summary',
    'A bar chart showing monthly totals of points going back 12 months. Filterable by PA org.',
    '64a42435-53ba-4085-b84b-286f401a6780',
    'kjvEpt',
    'KVATSkY',
    'Task Points Data (new)',
    'specialist_points_new',
    'specialist_points_new',
    'natural_key'
  ),
  (
    'points_specialists_by_week_old',
    'Points - Specialists',
    'By Week',
    'A table showing weekly totals of points going back 12 months.',
    'c499088a-8488-4839-b730-df1231e0f41b',
    'GrjAkg',
    'dZfMkdf',
    'Specialist Points Data (old)',
    'specialist_points_old',
    'specialist_points_old',
    'natural_key'
  ),
  (
    'points_specialists_by_week_new',
    'Points - Specialists',
    'By Week',
    'A table showing weekly totals of points going back 12 months.',
    '64a42435-53ba-4085-b84b-286f401a6780',
    'kjvEpt',
    'KVATSkY',
    'Task Points Data (new)',
    'specialist_points_new',
    'specialist_points_new',
    'natural_key'
  ),
  (
    'points_specialists_by_pa_org_processing_assistant_orgs',
    'Points - Specialists',
    'By PA Org',
    'A table showing total points by PA Org. I think it would be more effective if it were to show a monthly total for the current month that restarts on the 5th.',
    '49464eb8-41f0-499e-87dd-4a95f9341785',
    'dTpmk',
    'ea588bfe-9ea0-414a-9068-0e12f407251c',
    'Processing Assistant Orgs',
    'raw_only',
    null,
    'hash'
  ),
  (
    'points_specialists_by_pa_org_old',
    'Points - Specialists',
    'By PA Org',
    'A table showing total points by PA Org. I think it would be more effective if it were to show a monthly total for the current month that restarts on the 5th.',
    'c499088a-8488-4839-b730-df1231e0f41b',
    'GrjAkg',
    'dZfMkdf',
    'Specialist Points Data (old)',
    'specialist_points_old',
    'specialist_points_old',
    'natural_key'
  ),
  (
    'points_specialists_by_pa_org_new',
    'Points - Specialists',
    'By PA Org',
    'A table showing total points by PA Org. I think it would be more effective if it were to show a monthly total for the current month that restarts on the 5th.',
    '64a42435-53ba-4085-b84b-286f401a6780',
    'kjvEpt',
    'KVATSkY',
    'Task Points Data (new)',
    'specialist_points_new',
    'specialist_points_new',
    'natural_key'
  ),
  (
    'points_specialists_top_20_users_employee_data',
    'Points - Specialists',
    'Top 20 Users',
    'A top-20 ranking of employees with the most points where the employee''s default role is "Processor Assistant". I think it would be more effective if it were to show a monthly total for the current month that restarts on the 5th.',
    '49464eb8-41f0-499e-87dd-4a95f9341784',
    'dTpmk',
    '99cffdd8-c4c2-44d6-adf3-a39bc721903f',
    'Employee Data',
    'employees',
    'employees',
    'natural_key'
  ),
  (
    'points_specialists_top_20_users_old',
    'Points - Specialists',
    'Top 20 Users',
    'A top-20 ranking of employees with the most points where the employee''s default role is "Processor Assistant". I think it would be more effective if it were to show a monthly total for the current month that restarts on the 5th.',
    'c499088a-8488-4839-b730-df1231e0f41b',
    'GrjAkg',
    'dZfMkdf',
    'Specialist Points Data (old)',
    'specialist_points_old',
    'specialist_points_old',
    'natural_key'
  ),
  (
    'points_specialists_top_20_users_new',
    'Points - Specialists',
    'Top 20 Users',
    'A top-20 ranking of employees with the most points where the employee''s default role is "Processor Assistant". I think it would be more effective if it were to show a monthly total for the current month that restarts on the 5th.',
    '64a42435-53ba-4085-b84b-286f401a6780',
    'kjvEpt',
    'KVATSkY',
    'Task Points Data (new)',
    'specialist_points_new',
    'specialist_points_new',
    'natural_key'
  )
on conflict (sync_key)
do update set
  hub_page = excluded.hub_page,
  hub_visualization = excluded.hub_visualization,
  hub_visualization_description = excluded.hub_visualization_description,
  qlik_app_id = excluded.qlik_app_id,
  qlik_sheet_id = excluded.qlik_sheet_id,
  qlik_object_id = excluded.qlik_object_id,
  qlik_object_description = excluded.qlik_object_description,
  domain_name = excluded.domain_name,
  target_table_name = excluded.target_table_name,
  primary_key_strategy = excluded.primary_key_strategy,
  is_enabled = true,
  schedule_cron = '0 6 * * *';
